---
- hosts: dbservers
  become: yes
  roles:
#      - git.install
#      - mySQL.install

  tasks:
  -  name: installing mysql-server
     yum: name=mysql-server state=installed
     when: ansible_os_family == 'RedHat'
 
  -  name: installing mysql-server
     apt: name=mysql-server state=installed
     when: ansible_os_family == 'Debian'

  -  name: starting mysqld for centos
     service: name=mysqld state=started
     when: ansible_os_family == 'RedHat'
  
  -  name: starting mysql for ubuntu
     service: name=mysql state=started
     when: ansible_os_family == 'Debian'

  -  name: creating backup directory
     file: path=
           state=directory
           force=no
     
  -  name: moving sample template file
     template: src=
               dest=

  -
