---
# tasks file for VPwebservers
- name: installing httpd
  yum: name=httpd state=installed
  when: ansible_os_family == "RedHat" 
 
- name: starting httpd
  service: name=httpd state=started
  when: ansible_os_family == "RedHat" 

- name: moving template file
  template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf
  when: ansible_os_family == "RedHat" 

- name: installing apache2
  apt: name=apache2 state=installed
  when: ansible_os_family == "Debian" 
 
- name: starting apache2
  service: name=apache2 state=started
  when: ansible_os_family == "Debian" 
   
- name: moving template file
  template:
     src=apache2.j2
     dest=/etc/apache2/mods-available/mpm_prefork.conf
  when: ansible_os_family == "Debian" 

- name: moving sample template
  template: src=sample.j2 dest=/home/vagrant/sample
 
- name: creating ansible directory
  file: path={{doc_root}}/ansible state=directory

- name: moving index.html file
  template:
      src=index.j2 
      dest={{ doc_root }}/ansible/index.html mode=0644
  notify: restart apache/httpd

- name: iptables off
  service: name=iptables state=stopped
  when: ansible_os_family == "RedHat" 

- name: ufw off
  yum: name=ufw state=stopped
  when: ansible_os_family == "Debian" 