---
# handlers file for VPwebservers
  
- name: restart apache/httpd
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: restart apache/httpd
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"